import { chromium } from 'playwright'
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium' })
const p = await b.newPage({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 2 })
await p.goto('http://127.0.0.1:4173/', { waitUntil: 'networkidle' })
await p.evaluate(() => localStorage.clear())
await p.reload({ waitUntil: 'networkidle' })
await p.getByRole('button', { name: 'See a demo instead' }).click()
await p.waitForTimeout(3200)
const keep = p.getByRole('button', { name: 'Keep going' })
if (await keep.count()) await keep.click().catch(() => {})
await p.waitForTimeout(2600)
await p.goto('http://127.0.0.1:4173/#/activity', { waitUntil: 'networkidle' })
await p.waitForTimeout(700)
await p.screenshot({ path: 'shots/21-activity.png' })
await b.close()
