import { launch } from './browser.mjs'
const BASE = process.env.BASE ?? 'http://127.0.0.1:4173'
const b = await launch()
const p = await b.newPage({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 2 })
const errs = []
p.on('pageerror', e => errs.push(e.message))
p.on('console', m => { if (m.type() === 'error' && !/favicon|404/.test(m.text())) errs.push(m.text()) })
await p.goto(BASE, { waitUntil: 'networkidle' })
await p.evaluate(() => localStorage.clear())
await p.reload({ waitUntil: 'networkidle' })
await p.waitForTimeout(500)
await p.screenshot({ path: 'shots/n01-onboarding.png' })
await p.getByRole('button', { name: 'See a demo instead' }).click()
await p.waitForTimeout(3000)
const keep = p.getByRole('button', { name: 'Keep going' })
if (await keep.count()) await keep.click().catch(()=>{})
await p.waitForTimeout(2800)
const shot = async (hash, name) => {
  await p.goto(`${BASE}#/${hash}`, { waitUntil: 'networkidle' })
  await p.waitForTimeout(600)
  await p.screenshot({ path: `shots/${name}.png` })
}
await shot('home', 'n02-home')
await shot('vaults', 'n03-vaults')
await p.locator('.vaultcard').first().click(); await p.waitForTimeout(700)
await p.screenshot({ path: 'shots/n04-vault.png' })
await p.locator('.app__scroll').evaluate(el => el.scrollTo(0, 620)); await p.waitForTimeout(400)
await p.screenshot({ path: 'shots/n05-pace.png' })
await shot('quests', 'n06-goals')
await shot('progress', 'n07-progress')
await p.locator('.app__scroll').evaluate(el => el.scrollTo(0, 700)); await p.waitForTimeout(500)
await p.screenshot({ path: 'shots/n08-charts.png' })
await p.locator('.app__scroll').evaluate(el => el.scrollTo(0, 2100)); await p.waitForTimeout(500)
await p.screenshot({ path: 'shots/n09-badges.png' })
await shot('profile', 'n10-profile')

// Dark appearance, set through the real control.
await p.getByRole('button', { name: 'Dark', exact: true }).click()
await p.waitForTimeout(500)
await shot('home', 'n11-dark-home')
await shot('progress', 'n12-dark-progress')
await p.locator('.app__scroll').evaluate(el => el.scrollTo(0, 760)); await p.waitForTimeout(500)
await p.screenshot({ path: 'shots/n13-dark-charts.png' })
await shot('vaults', 'n14-dark-vaults')
await p.setViewportSize({ width: 1280, height: 900 })
await p.goto(`${BASE}#/home`, { waitUntil: 'networkidle' }); await p.waitForTimeout(600)
await p.screenshot({ path: 'shots/n15-desktop.png' })
console.log(errs.length ? 'ERRORS:\n' + errs.join('\n') : 'no runtime errors')
await b.close()
